language: python
os: linux
dist: xenial
python: 3.7

jobs:
  include:
    - stage: check
      install: pip install mypy==0.750 flake8==3.7.9
      script: make checks
    - stage: test
      install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get -y update && sudo apt-get -y install gcc-8 g++-8
      - pip install -r requirements.txt
      script:
        - CC=gcc-8 CXX=g++-8 python setup.py build
        - pip install .
        - make tests
